[package]
name = "mio-egal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.11.0"
mio = { version = "0.8.10", features = ["net"] }
